---

- name: "1.2.1 | PATCH | Ensure GPG keys are configured"
  block:
      - name: "1.2.1 | PATCH | Ensure GPG keys are configured"
        ansible.builtin.shell: "PKG=`rpm -qf {{ rpm_gpg_key }}` && rpm -q --queryformat \"%{PACKAGER} %{SIGPGP:pgpsig}\\n\" \"${PKG}\" | grep \"^{{ rpm_packager }}.*Key.ID.{{ rpm_key }}\""
        changed_when: false
  when:
      - rhel7cis_rule_1_2_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_1.2.1

- name: "1.2.2 | AUDIT | Ensure package manager repositories are configured"
  block:
      - name: "1.2.2 | AUDIT | Ensure package manager repositories are configured"
        ansible.builtin.shell: yum repolist
        changed_when: false
        register: repolist
        check_mode: false
        args:
            warn: false
        tags:
            - skip_ansible_lint

      - name: "1.2.2 | AUDIT | Ensure package manager repositories are configured"
        ansible.builtin.debug:
            msg:
                - "Please check against site policy repos listed below match expected:"
                - "{{ repolist.stdout_lines }}"
  when:
      - rhel7cis_rule_1_2_2
  tags:
      - level1-server
      - level1-workstation
      - audit
      - rule_1.2.2
      - skip_ansible_lint

- name: "1.2.3 | PATCH | Ensure gpgcheck is globally activated"
  block:
      - name: "1.2.3 | AUDIT | Ensure gpgcheck is globally activated"
        ansible.builtin.find:
            paths: /etc/yum.repos.d
            patterns: "*.repo"
        changed_when: false
        register: yum_repos

      - name: "1.2.3 | PATCH | Ensure gpgcheck is globally activated"
        ansible.builtin.replace:
            path: "{{ item.path }}"
            regexp: "^gpgcheck=0"
            replace: "gpgcheck=1"
        loop: "{{ yum_repos.files }}"
        loop_control:
            label: "{{ item.path }}"
  when:
      - rhel7cis_rule_1_2_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_1.2.3

- name: "1.2.4 | AUDIT | Ensure repo_gpgcheck is globally activated"
  block:
      - name: "1.2.4 | PATCH | Ensure repo_gpgcheck is globally activated | dnf.conf"
        ansible.builtin.lineinfile:
            path: /etc/dnf/dnf.conf
            regexp: '^repo_gpgcheck'
            line: repo_gpgcheck=1

      - name: "1.2.4 | AUDIT| Ensure repo_gpgcheck is globally activated | get repo files"
        ansible.builtin.find:
            paths: /etc/yum.repos.d
            patterns: "*.repo"
        register: repo_files

      - name: "1.2.4 | PATCH | Ensure repo_gpgcheck is globally activated | amend repo files"
        ansible.builtin.replace:
            path: "{{ item.path }}"
            regexp: '^repo_gpgcheck( |)=( |)0'
            replace: repo_gpgcheck=1
        loop: "{{ repo_files.files }}"
        loop_control:
            label: "{{ item.path }}"

  when:
      - rhel9cis_rule_1_2_4
      - not rhel9cis_rhel_default_repo or ansible_distribution != 'RedHat'
      - ansible_distribution != 'OracleLinux'
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_1.2.4

- name: "1.2.4 | AUDIT | Ensure Red Hat Subscription Manager connection is configured"
  ansible.builtin.shell: subscription-manager identity
  changed_when: false
  failed_when: false
  when:
      - ansible_distribution == "RedHat"
      - rhel7cis_rule_1_2_4
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_1.2.4

- name: "1.2.5 | PATCH | Disable the rhnsd Daemon"
  ansible.builtin.service:
      name: rhnsd
      state: stopped
      enabled: false
      masked: true
  when:
      - ansible_distribution == "RedHat" and not rhel7cis_rhnsd_required
      - rhel7cis_rule_1_2_5
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_1.2.5
